#!/usr/bin/env python3
from __future__ import annotations

import base64
import json
import sys

import requests


def main() -> None:
    if len(sys.argv) < 2:
        raise SystemExit("Usage: trigger_publish.py <tx_id>")

    tx_id = sys.argv[1]
    payload = {
        "tx_id": tx_id,
        "metadata": {
            "title": f"MatVerse Auto {tx_id[:8]}",
            "description": "Auto-generated by runtime",
            "creators": [{"name": "MatVerse"}],
        },
        "files": [base64.b64encode(b"runtime-auto-payload").decode("ascii")],
    }

    response = requests.post("http://localhost:8000/publish/fortified", json=payload, timeout=30)
    response.raise_for_status()
    print(json.dumps(response.json(), ensure_ascii=False))


if __name__ == "__main__":
    main()
